site_name: efxdev-docs
site_url: https://electroheadfx.github.io/mkdocs-material
site_author: Laurent Marques
site_description: >-
  Efxdev docs, exercices, tips for creative modern web platform standard with design system resilient UX, progressive enhancement, optimistic UI and accessibility
# Repository
repo_name: electroheadfx/efxdev-docs
repo_url: https://github.com/electroheadfx/efxdev-docs

copyright: Copyright &copy; 2022 - efxdesign / Laurent Marques

plugins:
  - glightbox
  - search
  - tags

markdown_extensions:
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true

  - attr_list
  - abbr
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.details
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  # custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    - header.autohide
    - navigation.indexes
    # - navigation.tabs.sticky 
  language: en
  logo: assets/images/efx-white.svg
  favicon: ./assets/favicon/favicon.png
  font:
    text: Roboto
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/grid-cards.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/electroheadfx
      name: Github

    - icon: fontawesome/solid/house
      link: laurent@efxdesign.fr
      name: My website

    - icon: fontawesome/regular/paper-plane
      link: mailto:<laurent@efxdesign.fr>
      name: Send me an email letting

  # avoid MKDocs build signature
  generator: false

#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Deutsch
#       link: /de/
#       lang: de

# Page tree
nav:
  - Home: /
  - Basis:
    - pages/basis/index.md
    - CSS: pages/basis/css.md
    - HTML: pages/basis/html.md
    - JS:
      - Basics: pages/basis/js-basics.md
      - Loop: pages/basis/js-loop.md
    - Node: pages/basis/node.md
    - Services: pages/basis/services.md
  - Advanced:
    - pages/advanced/index.md
    - JS:
      - pages/advanced/js/index.md
      - ES6 Utilities: pages/advanced/js/es6-utilities.md
      - Reduce Practices: pages/advanced/js/reduce-cases.md
      - Async / Await: pages/advanced/js/async-await.md
      - callback: pages/advanced/js/callback.md
      - Class: pages/advanced/js/class.md
      - Closures: pages/advanced/js/closures.md
      - Function currying: pages/advanced/js/currying.md
      - Generator: pages/advanced/js/generator.md
      - Iterator: pages/advanced/js/iterator.md
      - Map: pages/advanced/js/map.md
      - Promise: pages/advanced/js/promise.md
      - Set: pages/advanced/js/set.md
      - Interval: pages/advanced/js/setinterval.md
      - This: pages/advanced/js/this.md
      - This practices: pages/advanced/js/this-examples.md
      - TimeOut: pages/advanced/js/timeout.md


  # - Home: index.md
  # - Getting started:
  #   - Installation: getting-started.md
  #   - License: license.md
  #   - Changelog:
  #     - changelog/index.md
  #     - How to upgrade: upgrade.md
  # - Setup:
  #   - Changing the colors: setup/changing-the-colors.md
  #   - Adding a comment system: setup/adding-a-comment-system.md
  #   - Building for offline usage: setup/building-for-offline-usage.md
  #   - Extensions:
  #     - setup/extensions/index.md
  #     - Python Markdown: setup/extensions/python-markdown.md
  # - Reference:
  #   - reference/index.md
  #   - Admonitions: reference/admonitions.md
  #   - Annotations: reference/annotations.md
  #   - Buttons: reference/buttons.md
  # - Insiders:
  #   - insiders/index.md
  #   - Getting started:
  #     - Installation: insiders/getting-started.md
  #     - Changelog: insiders/changelog.md
  # - Blog:
  #   - blog/index.md
  #   - 2022:
  #     - blog/2022/chinese-search-support.md
  #   - 2021:
  #     - blog/2021/the-past-present-and-future.md
  #     - blog/2021/excluding-content-from-search.md
  #     - blog/2021/search-better-faster-smaller.md
