site_name: efxdev-docs
site_url: https://electroheadfx.github.io/efxdev-docs
site_author: Laurent Marques
site_description: >-
  Efxdev docs, exercices, tips for creative modern web platform standard with modern tools, design system resilient UX, progressive enhancement, optimistic UI and accessibility
# Repository
repo_name: electroheadfx/efxdev-docs
repo_url: https://github.com/electroheadfx/efxdev-docs

copyright: Copyright &copy; 2022 - efxdesign / Laurent Marques

plugins:
  - glightbox
  - search
  - tags

markdown_extensions:
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true

  - attr_list
  - abbr
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.details
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  # custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    - header.autohide
    - navigation.indexes
    # - navigation.tabs.sticky 
  language: en
  logo: assets/images/efx-white.svg
  category_illustraton: assets/images/whirl-web.svg
  favicon: ./assets/favicon/favicon.png
  font:
    text: Roboto
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/grid-cards.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/electroheadfx
      name: Github

    - icon: fontawesome/solid/house
      link: laurent@efxdesign.fr
      name: My website

    - icon: fontawesome/regular/paper-plane
      link: mailto:<laurent@efxdesign.fr>
      name: Send me an email letting

  # avoid MKDocs build signature
  generator: false

#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Deutsch
#       link: /de/
#       lang: de

  navIcons:
    basis:
      index:
        css: fontawesome/brands-css3-alt
        es6: fontawesome/solid-6
        events: material-television-ambient-light
        html: fontawesome/brands-html5
        js: fontawesome/brands-js
    advanced:
      index:
        javascript: material-language-javascript
        Typescript: material-language-typescript
        react: material-react
      javascript:
        async-await: fontawesome/solid-6
        callback: material-seat-legroom-reduced
        class: material-sync
        closures: material-call-merge
        es6-utilities: material-checkbox-multiple-blank-outline
        reduce-cases: material-vector-square-close
        currying: material-function
        generator: material-gradient-vertical
        iterator: material-account-cog
        map: material-access-point
        promise: fontawesome/solid-person-arrow-up-from-line
        set: fontawesome/solid-kitchen-set
        setinterval: material-clock-time-one
        this: material-human-handsup
        this-examples: material-text-box-search-outline
        timeout: material-timer-cog-outline
      typescript:
        basis: fontawesome/brands-microblog
        advanced: fontawesome/brands-adversal
        classes: material-sync
        react: material-react
      react:
        react-fetching: fontawesome/solid-crutch
        useRef-or-useState: material-state-machine

    tools:
      index:
        docker: fontawesome/brands-docker
        git: material-git
        node: material-nodejs
        services: material-room-service

# Page tree
nav:
  - Home: /efxdev-docs/
  - Basis:
    - pages/basis/index.md
    - CSS: pages/basis/css.md
    - HTML: pages/basis/html.md
    - Javascript:
      - pages/basis/js-basics.md
      - pages/basis/js-loop.md
  - Tools:
    - pages/tools/index.md
    - Docker:
      - pages/tools/docker/docker-start.md
      - pages/tools/docker/docker-exercice1.md
      - pages/tools/docker/docker-exercice2.md
    - pages/tools/git.md
    - pages/tools/node.md
    - Static site:
      - pages/tools/static/docusaurus-create.md
      - pages/tools/static/mkdocs-material.md
    - pages/tools/services.md
  - Advanced:
    - pages/advanced/index.md
    - Javascript:
      - pages/advanced/javascript/index.md
      - pages/advanced/javascript/async-await.md
      - pages/advanced/javascript/callback.md
      - pages/advanced/javascript/class.md
      - pages/advanced/javascript/closures.md
      - pages/advanced/javascript/es6-utilities.md
      - pages/advanced/javascript/reduce-cases.md
      - pages/advanced/javascript/currying.md
      - pages/advanced/javascript/generator.md
      - pages/advanced/javascript/iterator.md
      - pages/advanced/javascript/map.md
      - pages/advanced/javascript/promise.md
      - pages/advanced/javascript/set.md
      - pages/advanced/javascript/setinterval.md
      - pages/advanced/javascript/this.md
      - pages/advanced/javascript/this-examples.md
      - pages/advanced/javascript/timeout.md
    - Typescript:
      - pages/advanced/typescript/index.md
      - pages/advanced/typescript/basis.md
      - pages/advanced/typescript/advanced.md
      - pages/advanced/typescript/classes.md
      - pages/advanced/typescript/react.md
    - React:
      - pages/advanced/react/index.md
      - pages/advanced/react/react-fetching.md
      - pages/advanced/react/useRef-or-useState.md
    - Remix:
      - pages/advanced/remix/index.md
      - pages/advanced/remix/remix-fly.md
      - pages/advanced/remix/discord-discussions.md

  # - Home: index.md
  # - Getting started:
  #   - Installation: getting-started.md
  #   - License: license.md
  #   - Changelog:
  #     - changelog/index.md
  #     - How to upgrade: upgrade.md
  # - Setup:
  #   - Changing the colors: setup/changing-the-colors.md
  #   - Adding a comment system: setup/adding-a-comment-system.md
  #   - Building for offline usage: setup/building-for-offline-usage.md
  #   - Extensions:
  #     - setup/extensions/index.md
  #     - Python Markdown: setup/extensions/python-markdown.md
  # - Reference:
  #   - reference/index.md
  #   - Admonitions: reference/admonitions.md
  #   - Annotations: reference/annotations.md
  #   - Buttons: reference/buttons.md
  # - Insiders:
  #   - insiders/index.md
  #   - Getting started:
  #     - Installation: insiders/getting-started.md
  #     - Changelog: insiders/changelog.md
  # - Blog:
  #   - blog/index.md
  #   - 2022:
  #     - blog/2022/chinese-search-support.md
  #   - 2021:
  #     - blog/2021/the-past-present-and-future.md
  #     - blog/2021/excluding-content-from-search.md
  #     - blog/2021/search-better-faster-smaller.md
